source 'https://rubygems.org'

gem 'praxis'
gem 'rack', '~> 1.0'
gem 'rake'

gem 'activerecord'
gem 'activemodel'
gem 'activesupport'

group :development, :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'rubocop'
end
